name: Deploy FE (Container) to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - "20260302-UserManagement/fe/**"
      - ".github/workflows/deploy-fe.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push FE image
        uses: docker/build-push-action@v6
        with:
          context: ./20260302-UserManagement/fe
          file: ./20260302-UserManagement/fe/Dockerfile
          push: true
          build-args: |
            VITE_API_ENDPOINT=${{ secrets.VITE_API_ENDPOINT }}
          tags: |
            ${{ secrets.IMAGE_FE }}:${{ github.sha }}
            ${{ secrets.IMAGE_FE }}:latest

      - name: Deploy FE image to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEBAPP_FE_NAME }}
          images: ${{ secrets.IMAGE_FE }}:${{ github.sha }}
