name: Deploy FE (GHCR) to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - "20260302-UserManagement/fe/**"
      - ".github/workflows/deploy-fe.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login để PUSH image lên GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push FE image
        uses: docker/build-push-action@v6
        with:
          context: ./20260302-UserManagement/fe
          file: ./20260302-UserManagement/fe/Dockerfile
          push: true
          build-args: |
            VITE_API_ENDPOINT=${{ secrets.VITE_API_ENDPOINT }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/user-management-fe:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/user-management-fe:latest

      - name: Deploy FE image to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEBAPP_FE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FE }}
          images: ghcr.io/${{ github.repository_owner }}/user-management-fe:${{ github.sha }}
