name: Deploy BE (Container) to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - "20260302-UserManagement/be/**"
      - ".github/workflows/deploy-be.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push BE image
        uses: docker/build-push-action@v6
        with:
          context: ./20260302-UserManagement/be
          file: ./20260302-UserManagement/be/Dockerfile
          push: true
          tags: |
            ${{ secrets.IMAGE_BE }}:${{ github.sha }}
            ${{ secrets.IMAGE_BE }}:latest

      - name: Deploy BE image to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEBAPP_BE_NAME }}
          images: ${{ secrets.IMAGE_BE }}:${{ github.sha }}
